global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: pyraftkv
    metrics_path: /metrics

    static_configs:
      - targets:
          - node1:8000
          - node2:8000
          - node3:8000